### ISSUE TITLE
SDK Crashes on iOS 9

### ISSUE THREAD

**Issue by jjxtra** [Adonit/Adonit-iOS-SDK#32]
The SDK crashes on iOS 9, trying to use isConnected method of CBPeripheral. Adding a category for CBPeripheral fixes the problem, but the pen disconnects and doesn't appear to communicate connection events properly.

**Comment by antoniov72** [comment]
Compiling JotTouchSample with BITCODE with Xcode 7 fails due to BITCODE

d: '../JotTouchSDK.framework/JotTouchSDK(AdobeInkStylus.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jjxtra** [comment]
Crash is fixed with latest code.
